name: research_suite
description:  All-in-one solution for research data collection.
publish_to: 'THAung'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.10.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.10.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
